### ISSUE TITLE
Make VNC average template

### ISSUE THREAD

**Issue by bogovicj** [saalfeldlab/template-building#2]
## Preliminaries
- [x] Find lens correction parameters
- [x] Lens correct flies with VNC images
- [x] Stitch VNC images - (separate from brain)

#### Lens Parameters
Validated that the lens correction we ran before used [the parameters for scope 3.](https://github.com/saalfeldlab/confocal-lens/blob/master/src/main/java/org/janelia/saalfeldlab/confocallens/ConfocalLens.java#L385-L386)

## Build VNC templates
- [x] Build symmetric groupwise template 
- [ ] Build symmetric female-only groupwise template 
- [ ] Build symmetric male-only groupwise template 

## Possible VNC + brain template
- [ ] Try stitching VNCs along with brain
- [ ] Consider whether its possible to do a joint brain-vnc template

**Comment by axtimwalde** [comment]
Look at this...
